import type { SymbolSpec } from '../types/symbol'
import { DEFAULT_SYMBOL_SPEC, mergeSymbolSpec } from '../types/symbol'

/** 신규 종목: `mergeSymbolSpec({ symbol, displayName, … })` 로 풀 스펙을 만들고 이 객체에 추가 */
export const SYMBOL_REGISTRY: Record<string, SymbolSpec> = {
  BTCUSDT: mergeSymbolSpec({
    symbol: 'BTCUSDT',
    displayName: 'BTC/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.1,
    lotSize: 0.001,
    contractSize: 1,
    tickValue: 0.1,
    priceDecimals: 2,
    qtyDecimals: 4,
    defaultLeverage: 10,
    minQty: 0.001,
    maxQty: 500,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 97_250,
  }),
  ETHUSDT: mergeSymbolSpec({
    symbol: 'ETHUSDT',
    displayName: 'ETH/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.05,
    lotSize: 0.001,
    contractSize: 1,
    tickValue: 0.05,
    priceDecimals: 2,
    qtyDecimals: 4,
    defaultLeverage: 10,
    minQty: 0.001,
    maxQty: 10_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 3_542,
  }),
  SOLUSDT: mergeSymbolSpec({
    symbol: 'SOLUSDT',
    displayName: 'SOL/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.01,
    lotSize: 0.01,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 2,
    defaultLeverage: 15,
    minQty: 0.01,
    maxQty: 500_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 178.5,
  }),
  XRPUSDT: mergeSymbolSpec({
    symbol: 'XRPUSDT',
    displayName: 'XRP/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.0001,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.0001,
    priceDecimals: 4,
    qtyDecimals: 2,
    defaultLeverage: 10,
    minQty: 1,
    maxQty: 10_000_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 2.31,
  }),
  DOGEUSDT: mergeSymbolSpec({
    symbol: 'DOGEUSDT',
    displayName: 'DOGE/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.00001,
    lotSize: 10,
    contractSize: 1,
    tickValue: 0.00001,
    priceDecimals: 5,
    qtyDecimals: 2,
    defaultLeverage: 10,
    minQty: 10,
    maxQty: 50_000_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 0.1624,
  }),
  BNBUSDT: mergeSymbolSpec({
    symbol: 'BNBUSDT',
    displayName: 'BNB/USDT',
    marketType: 'crypto',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.05,
    lotSize: 0.001,
    contractSize: 1,
    tickValue: 0.05,
    priceDecimals: 2,
    qtyDecimals: 4,
    defaultLeverage: 10,
    minQty: 0.001,
    maxQty: 50_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 612.9,
  }),
  /** 지수 선물 스타일 (NQ 등 mock) */
  NASDAQ: mergeSymbolSpec({
    symbol: 'NASDAQ',
    displayName: 'NASDAQ 100 Fut',
    marketType: 'futures',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.25,
    lotSize: 1,
    contractSize: 1,
    tickValue: 5,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 5,
    minQty: 1,
    maxQty: 5_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 19_820,
  }),
  /** 금 선물 스타일 */
  GOLD: mergeSymbolSpec({
    symbol: 'GOLD',
    displayName: 'Gold Fut',
    marketType: 'commodity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.1,
    lotSize: 1,
    contractSize: 1,
    tickValue: 10,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 20,
    minQty: 1,
    maxQty: 2_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 2_345.6,
  }),
  /** 미국 주식 예시 — 주 단위 */
  AAPL: mergeSymbolSpec({
    symbol: 'AAPL',
    displayName: 'Apple Inc.',
    marketType: 'stock',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.01,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 212.5,
  }),
}

export const STANDARD_SYMBOLS = [
  'BTCUSDT',
  'ETHUSDT',
  'SOLUSDT',
  'XRPUSDT',
  'DOGEUSDT',
  'BNBUSDT',
  'NASDAQ',
  'GOLD',
  'AAPL',
] as const

export function getSymbolSpec(symbol: string | undefined | null): SymbolSpec {
  if (!symbol) return { ...DEFAULT_SYMBOL_SPEC }
  const key = symbol.toUpperCase()
  const hit = SYMBOL_REGISTRY[key]
  if (hit) return hit
  return mergeSymbolSpec({
    ...DEFAULT_SYMBOL_SPEC,
    symbol: key,
    displayName: key,
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
  })
}

export function isListedSymbol(symbol: string): boolean {
  return symbol.toUpperCase() in SYMBOL_REGISTRY
}
